---
title: "Produção Intelectual"
---

## Artigos científicos

-  Durgante FM, CC Vasconcelos, HL Hadlich, CL Mallmann, RO Perdiz, KCM Cunha, C Paquini, K Torralvo, M Hopkins, J Schöngart, MTF Piedade, PA Sá, MLG Conde, & F Wittmann. **Portable spectrometer as a low-cost tool for tree species identification in herbaria and field studies**. Submetido para publicação, 2025.

-   Hadlich HL, J Schöngart, F Wittmann, CC Vasconcelos, CL Mallmann, MLG Conde, PA Sá, LO Demarchi, GB Mori, MTF Piedade, & FM Durgante. 2025. **Exploring the potential of field spectroscopy for tree species identification in different Amazonian forest ecosystems**. *Global Ecology and Conservation*, 54: e03970. DOI: <https://doi.org/10.1016/j.gecco.2025.e03970>

-   Cavender-Bares J, DM White, NI Ahlstrand, M Austin, D Bastianelli, S Bazan, K Boughalmi, W Cardinal-McTeague, E Chacón-Madrigal, TLP Couvreur, C Davis, FM Durgante, OM Grace, JA Guzmán, K Hansen, MS Hernández-Leal, MJG Hopkins, R Jackson, S Kothari, AK Lee, E Léveillé-Bourret, J Pinto-Ledezma, NLQ Casaverde, JE Meireles, B Neto-Bradley, CO Nichodemus, RH Ree, M Schmull, DE Soltis, PS Soltis, H Tuomisto, S Ustin, & CC Vasconcelos. 2025. **Next-generation specimen digitization: capturing reflectance spectra from the world's herbaria for modeling plant biology across time, space, and taxa**. *New Phytologist* (version of record). DOI: <https://doi.org/10.1111/nph.70645>

-   Vasconcelos CC, IDK Ferraz, FM Durgante, F Wittmann, J Schöngart, MTF Piedade, JLC Camargo, & MH Terra-Araujo. 2025. ***Ecclinusa nervosa*** **(Sapotaceae, Chrysophylloideae), a new species discovered in Central Amazonia**. *Systematic Botany* 50(1): 55-66. DOI: <https://doi.org/10.1600/036364425X17466502618821>

## Material instrucional

-   White DM, NI Ahlstrand, MW Austin, D Bastianelli, S Bazan, K Boughalmi, W Cardinal-McTeague, TLP Couvreur, F Durgante, OM Grace, JA Guzmán Q, K Hansen, M Hopkins, R Jackson, JA Kennedy, S Kothari, AK Lee, É Léveillé-Bourret, JE Meireles, BM Neto-Bradley, CO Nichodemus, NL Quinteros Casaverde, C Rodrigues-Vaz, M Schmull, PS Soltis, D Spalink, CC Vasconcelos, JL Viana, H Tuomisto, T Wells, & J Cavender-Bares. 2025. **IHerbSpec Protocol**. *Zenodo*. DOI: <https://doi.org/10.5281/zenodo.15849668>

-   Vasconcelos CC & FM Durgante. 2025. **R codes and datasets used in the course 'Herbarium Spectroscopy with MicroNIR: theory and practice'**. *Zenodo*. DOI: <https://doi.org/10.5281/zenodo.15531968>


## Participação em eventos

- Durgante FM. Palestra: **Spectral herbarium from INPA: equipment, methods and applications to species identification**. *In:* International Herbarium Spectral Digitization (IHerbSpec) Working Group, Harvard University Herbaria, Cambridge, MA, USA. Maio/2025.

- Torralvo KC. Minicurso: **Teoria e delineamento de coletas espectrais de Infravermelho Próximo (NIR) para reconhecimento da biodiversidade**. *In:* 21° Simpósio Sobre Conservação e Manejo Participativo na Amazônia, Instituto de Desenvolvimento Sustentável Mamirauá, Tefé, AM, Brasil. Julho/2025. 

- Durgante FM, JL Viana, CC Vasconcelos, HL Hadlich, & CL Mallmann. Simpósio: **Espectroscopia aplicada à identificação de plantas: avanços para herbários, manejo e conservação**. *In:* 75° Congresso Nacional de Botânica e 39ª Reunião Nordestina de Botânica, Universidade Federal do Delta do Parnaíba (UFDPar), Parnaíba, PI, Brasil. Agosto/2025. 

- Torralvo KC, R Holanda, IY Fernandes, AP Lima, C Pasquini, FM Durgante, & WE Magnusson. Apresentação oral: **Uso da espectroscopia nir no reconhecimento de anuros: método, testes de eficiência e perspectivas de aplicação incluindo equipamento de baixo-custo**. *In:* XI Congresso Brasileiro de Herpetologia, Sociedade Brasileira de Herpetologia, Manaus, AM, Brasil. Agosto/2025. 

- Lima KT, KAL Santos, JB Moreira, CC Vasconcelos, FM Durgante, & HS Pereira. Pôster: **Espectroscopia NIR aplicada à identificação de etnovariedades de *Ananas comosus***. *In:* XXI Semana de Agronomia (SEMAGRO), Universidade Federal do Amazonas (UFAM), Manaus, AM, Brasil. Outubro/2025.

- Os nossos bolsistas do PIBIC/INPA — Eduardo Cunha, Eliandra Rodrigues e Yasmin Guedes — participaram da 22ª Semana Nacional de Ciência e Tecnologia do INPA. Eles integraram a equipe do Herbário INPA na divulgação das atividades desenvolvidas na coleção, apresentando ao público um pouco do trabalho científico que realizam no dia a dia. Outubro/2025.

##  Orientações em andamento

- Maria Clara Abreu Mota de Oliveira Ramos Ferro (INPA). Mestrado PPGBOT-INPA: **Material de fundo importa? Testando padrões de reflectância na espectroscopia de folhas herborizadas em diferentes tipos de materiais de fundo e sua eficácia na discriminação de espécies**. Início: Março/2025. Orientação: Flávia Durgante.

- Eduardo Leandro Cunha (UFAM). PIBIC-INPA: **Inteligência artificial aplicada à taxonomia de *Ecclinusa* (Sapotaceae): validação espectral e interoperabilidade com espectrômetros portáteis**. Início: Setembro/2025. Supervisão: Michael Hopkins.

- Eliandra Rodrigues Ferreira (Estácio). PIBIC-INPA: **Desenvolvimento de bibliotecas espectrais para identificação de espécies no Herbário INPA: um estudo com Fabaceae e Meliaceae**. Início: Setembro/2025. Orientação: Michael Hopkins.

- Yasmin Jéssica Guimarães Guedes (UFAM). PIBIC-INPA: **Construção de biblioteca espectral aplicada à identificação de Bignoniaceae no Herbário INPA**. Início: Setembro/2025. Orientação: Michael Hopkins.

## Disciplinas

- Durgante FM. Disciplina: **Tópico Especial - Uso de espectroscopia para reconhecimento da Biodiversidade**, realizada no período de 25/08 a 06/09/2025 (60 horas). Instituto Nacional de Pesquisas da Amazônia, curso de mestrado e doutorado do Programa de Pós-Graduação em Botânica (PPGBOT).


## Aplicações web

-  Vasconcelos CC, KCM Cunha, & FM Durgante. 2025. `iscreader app` (<https://spectrapop.shinyapps.io/iscreaderapp/>) - Aplicação web desenvolvida para facilitar a importação, visualização e processamento de arquivos brutos gerados pelo espectrômetro portátil MicroNIR modelo NIR-S-G1 (InnoSpectra Corp).

-  Vasconcelos CC & FM Durgante. 2025. `multispecreader app` (<https://spectrapop.shinyapps.io/multispecreaderapp/>) - Aplicação web desenvolvida para facilitar a importação, visualização e processamento de arquivos brutos gerados pelos espectrômetros Antaris™ II (FT-NIR Analyzer, Thermo Fisher Scientific Inc.) e ASD FieldSpec® (Malvern Panalytical Ltd).